### ISSUE TITLE
生成失败,收到报错.

### ISSUE THREAD

**Issue by 7mue3ttT** [ygh3279799773/streamer-card#1]
`/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93
    #error = new Errors_js_1.ProtocolError();
             ^

ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
    at new Callback (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
    at CallbackRegistry.create (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
    at Connection._rawSend (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
    at CdpCDPSession.send (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
    at #evaluate (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:356:50)
    at async ExecutionContext.evaluate (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:271:16)
    at async IsolatedWorld.evaluate (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:16)
    at async CdpFrame.evaluate (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:338:20)
    at async CdpPage.evaluate (/Users/ming/Documents/host/streamer-card/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:826:20)`

**Comment by someone1128** [comment]
要不加个微信，有空我远程给你看一下解决：chatgpt0ai0041128

**Comment by someone1128** [comment]
确实有时候会加载比较久，目前我们也在解决 API 的一些 bug，比如一些 api 参数失效，无法切换颜色，内容无法通过 \n 进行换行，解决完参数失效问题，接下来我们会考虑如何让 api 请求速度更快

**Comment by someone1128** [comment]
我写了一个问题，你可以在里面看到我们的更新计划和最近更新：https://flowus.cn/share/b8f12c14-1042-42f3-8281-6149f20e3e95

**Comment by ygh3279799773** [comment]
关闭vpn或者延迟apipost请求超时时间，如果是非中国大陆用户的话需要将代码中的服务器切换至我们海外版本
