### ISSUE TITLE
服务器启动报错

### ISSUE THREAD

**Issue by alterem** [ygh3279799773/streamer-card#6]
服务器启动报错

```bash
node example1.js 
监听端口 3003...
/root/streamer-card/node_modules/puppeteer-cluster/dist/Cluster.js:119
                throw new Error(`Unable to launch browser, error message: ${err.message}`);
                      ^

Error: Unable to launch browser, error message: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-126.0.6478.126/chrome-linux64/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Cluster.<anonymous> (/root/streamer-card/node_modules/puppeteer-cluster/dist/Cluster.js:119:23)
    at Generator.throw (<anonymous>)
    at rejected (/root/streamer-card/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.0
```

**Comment by someone1128** [comment]
你使用的 linuxt 版本是多少？可以看看这个 https://blog.csdn.net/weixin_46184095/article/details/140297726?spm=1001.2014.3001.5501 一些错误问题在这里有写
